import 'semantic-ui-css/semantic.min.css';

import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div style={{ marginTop: '5em' }}>{children}</div>
      </body>
    </html>
  );
}
